---
# This playbook deploys the entire Mesos cluster infrastructure.
# RUN: ansible-playbook --ask-sudo-pass -i hosts site.yml
# RUN only mesos-master: ansible-playbook --ask-sudo-pass -i hosts site.yml --tags "common,zookeeper"
# RUN only mesos-master: ansible-playbook --ask-sudo-pass -i hosts site.yml --tags "common,mesos-master"
# RUN only mesos-slave: ansible-playbook --ask-sudo-pass -i hosts site.yml --tags "common,mesos-master"
# RUN only marathon: ansible-playbook --ask-sudo-pass -i hosts site.yml --tags "common,marathon"

- include: common.yml

# hosts in the zookeeper group
- name: deploy and configure the zookeeper hosts
  hosts: zookeepers
  sudo: True

  roles:
    - { role: zookeeper, zookeeper_action: "install", tags: ["zookeeper"] }

# hosts in both the mesos_masters and mesos_slaves groups
- name: deploy and configure mesos and slave hosts
  hosts: mesos_masters:&mesos_slaves
  sudo: True

  roles:
    - { role: mesos, mesos_install_mode: "master-slave", tags: ["mesos-master", "mesos-slave"] }
    - { role: docker, tags: ["docker"] }

# hosts in only the mesos_masters group
- name: deploy and configure the mesos master-only hosts
  hosts: mesos_masters:!mesos_slaves
  sudo: True

  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }

# hosts in only the mesos_slaves group
- name: deploy and configure the mesos slave-only hosts
  hosts: mesos_slaves:!mesos_masters
  sudo: True

  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
    - { role: docker, tags: ["docker"] }

  # hosts in both the mesos_masters and marathon groups
- name: deploy and configure mesos and marathon hosts
  hosts: marathon:&mesos_masters
  sudo: True

  roles:
    - { role: marathon, marathon_only: False, tags: ["marathon"] }

  # hosts in only the marathon group
- name: deploy and configure marathon-only hosts
  hosts: marathon:!mesos_masters
  sudo: True

  roles:
    - { role: marathon, marathon_only: True, tags: ["marathon"] }

# remove ZooKeeper from master-only, slave-only, or marathon-only hosts
- name: remove zookeeper from master-only host(s)
  hosts: mesos_masters:!zookeepers
  sudo: True

  roles:
    - { role: zookeeper, zookeeper_action: "remove", tags: ["zookeeper"] }

- name: remove zookeeper from slave-only host(s)
  hosts: mesos_slaves:!zookeepers
  sudo: True

  roles:
    - { role: zookeeper, zookeeper_action: "remove", tags: ["zookeeper"] }

- name: remove zookeeper from marathon-only host(s)
  hosts: marathon:!zookeepers
  sudo: True

  roles:
    - { role: zookeeper, zookeeper_action: "remove", tags: ["zookeeper"] }

