---
# tasks file for mesos role

# Install Mesosphere Mesos package
- name: Install mesos package
  #apt: pkg={{item}} state=present update_cache=yes
  apt: pkg={{item}} state=present
  with_items:
    - mesos={{ mesos_pkg_version }}
  sudo: yes

# used for leader election amongst masters
- name: Set ZooKeeper URL
  copy:
    content: "{{zookeeper_url}}/mesos"
    dest: /etc/mesos/zk
    mode: 0644
  sudo: yes

# Tasks for Master nodes
- name: Disable the Mesos Slave service
  copy:
    content: "manual"
    dest: /etc/init/mesos-slave.override
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "master"

- name: Set Mesos Master hostname
  copy:
    content: "{{mesos_local_address}}"
    dest: /etc/mesos-master/hostname
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Set Mesos Master ip
  copy:
    content: "{{mesos_local_address}}"
    dest: /etc/mesos-master/ip
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

  # The Mesos quorum value is based on the number of Mesos Masters. Take the
  # number of masters, divide by 2, and round-up to nearest integer. For example,
  # if there are 1 or 2 masters the quorum count is 1. If there are 3 or 4
  # masters then the quorum count is 2. For 5 or 6 masters it's 3 and so on.
- name: Set Mesos Master quorum count
  template: src=quorum.j2 dest=/etc/mesos-master/quorum mode=0644
  sudo: yes
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Set Mesos Master Cluster name
  copy:
    content: "{{mesos_cluster_name}}"
    dest: /etc/mesos-master/cluster
    mode: 0644
  sudo: yes
  notify:
    - Start mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

# Tasks for Slave nodes
- name: Disable the Mesos Master service
  copy:
    content: "manual"
    dest: /etc/init/mesos-master.override
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "slave"

- name: Set Mesos Slave hostname
  copy:
    content: "{{mesos_local_address}}"
    dest: /etc/mesos-slave/hostname
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Set Mesos Slave ip
  copy:
    content: "{{mesos_local_address}}"
    dest: /etc/mesos-slave/ip
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Set Mesos Slave isolation
  copy:
    content: "cgroups/cpu,cgroups/mem"
    dest: /etc/mesos-slave/isolation
    mode: 0644
  sudo: yes
  notify:
    - Start mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

# mesos-docker
- name: Set Mesos Slave using Docker
  copy:
    content: "docker,mesos"
    dest: /etc/mesos-slave/containerizers
    mode: 0644
  sudo: yes
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Set Mesos Slave using Docker increase timeout
  copy:
    content: "5mins"
    dest: /etc/mesos-slave/executor_registration_timeout
    mode: 0644
  sudo: yes
  notify:
    - Restart mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

# open ports for mesos cassandra
# - name: Expand port range for Mesos Cassandra
#   lineinfile:
#     create: yes
#     dest: /etc/mesos-slave/resources
#     regexp: "ports"
#     line: "ports:[31000-32000,7000-7001,7199-7199,9042-9042,9160-9160]"
#   sudo: yes
#   notify:
#     - Restart mesos-slave
#   when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

