---
# Common tasks for all Mesos cluster nodes
- name: Add key for Mesosphere repository
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE56151BF state=present
  sudo: yes

- name: Determine Linux distribution distributor
  shell: lsb_release -is | tr '[:upper:]' '[:lower:]'
  register: release_distributor

- name: Determine Linux distribution codename
  command: lsb_release -cs
  register: release_codename

- name: Add Mesosphere repository to sources list
  copy:
    content: "deb http://repos.mesosphere.io/{{release_distributor.stdout}} {{release_codename.stdout}} main"
    dest: /etc/apt/sources.list.d/mesosphere.list
    mode: 0644
  sudo: yes

- name: Add apt proxy
  copy:
    content: 'Acquire::http::Proxy "http://{{ apt_proxy_ip }}:{{ apt_proxy_port }}/";'
    dest: /etc/apt/apt.conf.d/01proxy
    mode: 0644
  sudo: yes

